version: "3"

services:
  database:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: pgdb
    volumes:
      - "./data/sql:/docker-entrypoint-initdb.d/:ro"
    ports:
      - "5436:5432"